-- Classic 1.60: page texts read in ymir sniffs of the official beta (classic_re/sniff/sniff_pages.py)
DELETE FROM `page_text` WHERE `ID` IN (10322,10323,10324,10732,10733,10734,10735);
INSERT INTO `page_text` (`ID`,`Text`,`NextPageID`,`PlayerConditionID`,`Flags`,`VerifiedBuild`) VALUES
(10322,'The cult hit us by surprise. Raani never saw it coming and Arvensus took a sword to the gut. For my part, I took a lightning bolt to the chest and blacked out. They never bothered to finish me off... I guess they assumed my wounds would do me in. When it\'s all said and done, I suspect they might.',10323,0,0,70124),
(10323,'As soon as the fighting stopped, they started moving massive crates of windstones to the top of the tower. The leader, some kind of priest, said something about a ritual.\r\n\r\nI\'m writing this note just in case I don\'t make it back to Shen\'dar to warn Aonda, but they are doing something here. Something bad.',10324,0,0,70124),
(10324,'If anyone finds this, please, do your best to stop them. There were only a few left at the tower when I scribbled this note and crawled away.\r\n\r\nAlso, try and get Raani\'s lucky feather from his body. He liked to tell tall tales about how he plucked it from some kind of firebird and I think he\'d want to make sure that it made its way back home.\r\n\r\nIf you are also able to retrieve Arvensus Shadowsong\'s family signet from his body, please do so. High Elder Shadowsong is his uncle and he would want it to be returned to the family.',0,0,0,70124),
(10732,'<You touch the small white crystal and you can hear faint sounds on the wind. This is an audio recording of some sort.>\r\n\r\n"The Rebellion in Eldre\'Thalas, Part 1"',10733,0,0,70124),
(10733,'"In the days immediately following the turmoil at the Well of Eternity, there was much unrest in Eldre\'Thalas. The demonic forces that poured from the Well nearly overwhelmed the beleaguered elvish kingdoms, ravaging the land and killing indiscriminately. If not for the intervention of the demigod Goldrinn and the sacrifice of countless kaldorei heroes, the kingdom of Eldre\'Thalas would surely have been overrun and destroyed."',10734,0,0,70124),
(10734,'"After the climax of the war and the Great Sundering of Kalimdor, the new reality of a world bereft of the sustaining magic on which our people depended quickly became apparent. The ruling house of Eldre\'Thalas--House Tortheldrin--rapidly set plans in motion to ensure stability and continuity of our way of life. However, the methods they intended to employ left many deeply concerned."',10735,0,0,70124),
(10735,'"The young Prince Tortheldrin intended to build a network of crystalline foci and use them to siphon and shape a new font of power for our people to draw upon. The point of contention for many was that he intended to use the very power that nearly destroyed our world to accomplish this. He meant to siphon this power from a demon world within the Twisting Nether itself. \r\n\r\nMany rightly feared this could open a new door through which demonic entities might gain once again access to our world."',0,0,0,70124);
